from __future__ import annotations

from notability2pdf_lib.archive import KeyedArchive, UID
from notability2pdf_lib.cli import default_output_dir, default_output_path, main, parse_args
from notability2pdf_lib.constants import (
    DEFAULT_CONTENT_INSET_RATIO,
    DEFAULT_EXPORT_WIDTH_PT,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_PAGE_COLOR,
    DEFAULT_PAGE_RATIO,
    DEFAULT_RULE_COLOR,
    DEFAULT_TEXT_COLOR,
    DEFAULT_TEXT_TOP_DOC,
    EXPORT_WIDTHS_PT,
    FONT_FALLBACKS,
    STROKE_STYLE_HIGHLIGHTER,
    STROKE_STYLE_NOT_EXPORTED,
    STROKE_STYLE_PEN,
    STROKE_STYLE_PENCIL,
)
from notability2pdf_lib.converter import (
    convert_note_folder_to_pdfs,
    convert_note_to_pdf,
    convert_note_to_raster_pdf,
    iter_note_files,
    output_path_for_note,
)
from notability2pdf_lib.fonts import load_font, measure_text_px, resolve_font_path
from notability2pdf_lib.models import EmbeddedPdfPage, MediaImage, NoteDocument, StrokeCurve, TextSpan, TextStyle
from notability2pdf_lib.parser import (
    choose_export_width,
    choose_thumbnail_entry,
    default_text_style,
    find_bundle_root,
    load_note_document,
    parse_content_inset_doc,
    parse_curves,
    parse_handwriting_color,
    parse_line_spacing_doc,
    parse_media_images,
    parse_pair,
    parse_range,
    parse_text,
    parse_text_color,
    resample_values,
    split_curve_into_pages,
    unpack_numeric_blob,
)
from notability2pdf_lib.pdf import write_pdf
from notability2pdf_lib.rendering import (
    build_style_map,
    darken_alpha_composite,
    draw_highlighter_curve,
    draw_page_background,
    draw_pen_curve,
    draw_pencil_curve,
    draw_round_polyline,
    render_curves,
    render_media,
    render_note_pages,
    render_text,
    stroke_points_px,
)
from notability2pdf_lib.vector_pdf import write_svg_pages, write_vector_pdf

__all__ = [
    "DEFAULT_CONTENT_INSET_RATIO",
    "DEFAULT_EXPORT_WIDTH_PT",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_PAGE_COLOR",
    "DEFAULT_PAGE_RATIO",
    "DEFAULT_RULE_COLOR",
    "DEFAULT_TEXT_COLOR",
    "DEFAULT_TEXT_TOP_DOC",
    "EXPORT_WIDTHS_PT",
    "FONT_FALLBACKS",
    "EmbeddedPdfPage",
    "KeyedArchive",
    "MediaImage",
    "NoteDocument",
    "STROKE_STYLE_HIGHLIGHTER",
    "STROKE_STYLE_NOT_EXPORTED",
    "STROKE_STYLE_PEN",
    "STROKE_STYLE_PENCIL",
    "StrokeCurve",
    "TextSpan",
    "TextStyle",
    "UID",
    "build_style_map",
    "choose_export_width",
    "choose_thumbnail_entry",
    "convert_note_to_pdf",
    "convert_note_folder_to_pdfs",
    "convert_note_to_raster_pdf",
    "darken_alpha_composite",
    "default_output_dir",
    "default_output_path",
    "default_text_style",
    "draw_highlighter_curve",
    "draw_page_background",
    "draw_pen_curve",
    "draw_pencil_curve",
    "draw_round_polyline",
    "find_bundle_root",
    "iter_note_files",
    "load_font",
    "load_note_document",
    "main",
    "measure_text_px",
    "parse_args",
    "parse_content_inset_doc",
    "parse_curves",
    "parse_handwriting_color",
    "parse_line_spacing_doc",
    "parse_media_images",
    "parse_pair",
    "parse_range",
    "parse_text",
    "parse_text_color",
    "output_path_for_note",
    "render_curves",
    "render_media",
    "render_note_pages",
    "render_text",
    "resample_values",
    "resolve_font_path",
    "split_curve_into_pages",
    "stroke_points_px",
    "unpack_numeric_blob",
    "write_pdf",
    "write_svg_pages",
    "write_vector_pdf",
]


if __name__ == "__main__":
    raise SystemExit(main())
